### ISSUE TITLE
Game not loading

### ISSUE THREAD

**Issue by imhotep** [triceam/PhoneGap-Legends#1]
See screenshot
![android](https://f.cloud.github.com/assets/93032/293122/7938ed64-9343-11e2-80e1-ef38b94fcd3f.png)

**Comment by triceam** [comment]
Is this using PhoneGap Build?  If so, it's just b/c I need to switch it over to include the PG 2.3 JS file.  Currently, it has 2.5, which I used locally.  If you include the 2.3 JS file, it should work fine.  This is already a known issue, & I'll be updating this on Monday

**Comment by imhotep** [comment]
No, it was not using PhoneGap Build. I built it locally.

**Comment by triceam** [comment]
Weird... any error messages?

**Comment by triceam** [comment]
Android, or iOS?  I forgot to mention, I've only tested on Android & iOS.

**Comment by triceam** [comment]
Weird... I was seeing the same thing when compiling via Build.  I added a global error handler, now it runs fine for me (Android is where I was seeing the issue).  Try pulling the latest, and recompile.

**Comment by triceam** [comment]
Closing the issue... I am able to do full round trip from github->PG build->device.  Please let me know if you continue to experience problems.
