### ISSUE TITLE
no cordova.js

### ISSUE THREAD

**Issue by 0312birdzhang** [triceam/PhoneGap-Legends#4]

**Comment by triceam** [comment]
ummm.. were you trying to report a bug?

**Comment by 0312birdzhang** [comment]
Sorry for report this.It's a phonegap project not an html5 project.

**Comment by triceam** [comment]
that was written with an older version of phonegap, you might have to update the structure somewhat

**Comment by 0312birdzhang** [comment]
Yeah,i add cordova.js at root directory and it runs very well.
